# Generated by Django 3.1.1 on 2021-01-06 19:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_course_img_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='course',
            name='intro',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=1, null=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('Publier', 'publier'), ('Corbeille', 'corbeille')], default='publier', max_length=13),
        ),
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.CharField(choices=[('Débutant', 'Débutant'), ('Intermédiaire', 'Intermédiaire')], max_length=13),
        ),
    ]
