# Generated by Django 3.1.1 on 2021-01-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_auto_20210106_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.CharField(choices=[('Débutant', 'debutant'), ('intermediaire', 'Intermédiaire')], max_length=13),
        ),
    ]
