# Generated by Django 3.1.1 on 2021-01-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0005_auto_20210107_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('Publier', 'publier'), ('Corbeille', 'corbeille')], default='publier', max_length=13),
        ),
    ]
