# Generated by Django 3.1.1 on 2021-01-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0008_auto_20210111_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='also_send',
            field=models.BooleanField(default=False),
        ),
    ]
