# Generated by Django 3.1.1 on 2021-01-15 10:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0010_auto_20210112_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
