# Generated by Django 3.1.6 on 2021-02-18 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0015_auto_20210218_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='mail_send',
        ),
    ]
