# Generated by Django 3.1.6 on 2021-03-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0016_remove_course_mail_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='comments',
            field=models.TextField(verbose_name='Laisser un commentaire'),
        ),
    ]
