# Generated by Django 3.1.6 on 2021-03-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0018_auto_20210327_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('Course', 'cours'), ('Tutoriels', 'tutoriels')], default='cours', max_length=13),
        ),
    ]
