# Generated by Django 3.1.6 on 2021-03-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0019_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('Publier', 'publier'), ('Corbeille', 'corbeille')], default='Corbeille', max_length=13),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('Course', 'cours'), ('Tutoriels', 'tutoriels')], default='Course', max_length=13),
        ),
    ]
