# Generated by Django 3.1.6 on 2021-03-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quize', '0002_auto_20210319_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quize',
            name='min_score',
        ),
        migrations.AddField(
            model_name='result',
            name='appreciation',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='min_score',
            field=models.IntegerField(default=50),
        ),
    ]
