# Generated by Django 3.1.6 on 2021-03-20 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quize', '0004_result_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='number_of_tentative',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserValidQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=False)),
                ('quize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quize.quize')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
