"""
Django settings for pythonic project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/

"""
from pathlib import Path
from os import path as p, environ

from django.core.exceptions import ImproperlyConfigured

def get_secret(name, default=None):
    try:
        return environ[name]
    except KeyError:
        if default is None:
            raise ImproperlyConfigured(" environ error ")
        else:
            return default


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'igl%fkjn0!c!9#9p(rb7(f#ou03(giz6alh%daz7*o&c)_tw+m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["pythonnull.herokuapp.com", "localhost", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "posting",
    "ckeditor",
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pythonic.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pythonic.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

#developement databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

#postgres://lvuxbbjqfwnlco:547f1007c32d335f4404f53bd85fdae9ef5afb08ab4cc43faf2e4d1ebb14c777@ec2-54-75-244-161.eu-west-1.compute.amazonaws.com:5432/dlhfb4mojael7
# #production database
# DATABASES = {

#     'default': {

#         'ENGINE': 'django.db.backends.postgresql_psycopg2',

#         'NAME': 'dlhfb4mojael7',

#         'USER': 'lvuxbbjqfwnlco',

#         'PASSWORD': '547f1007c32d335f4404f53bd85fdae9ef5afb08ab4cc43faf2e4d1ebb14c777',

#         'HOST': 'ec2-54-75-244-161.eu-west-1.compute.amazonaws.com',

#         'PORT': 5432,

#     }

# }


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
STATIC_ROOT = p.join(BASE_DIR, "staticfiles")

MEDIA_URL = '/media/'
MEDIA_ROOT = p.join(BASE_DIR, "media")

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    p.join(BASE_DIR, "static"),
] 


CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Basic',
        'skin':'moono',
        'toolbar_Basic': 
             [
                 ['CodeSnippet'],
                 ['TextColor', 'BGColor','Maximize', 'ShowBlocks','Bold', "Table", "Smiley", "HorizontalRule", "Link",'Styles', 'Format', 'Font', 'FontSize' "SpecialChar","Image", "PageBreak", "Iframe"],
                  # here
             ], 'extraPlugins': ['codesnippet','ajax'],
        'width':'auto',
        # "update":['image','update','table','HorizontalRule', 'Smiley', "SpecialChar","CodeSnippet"], 'extraPlugins': 'codesnippet',
    },
    'special': 
        {'toolbar': 'Special', 'height': 500,
         'toolbar_Special': 
             [
                 ['Bold'],
                 ['CodeSnippet'], # here
             ], 'extraPlugins': 'codesnippet', # here
         },
    'extrait': {
        'toolbar': 'Basic',
         'toolbar_Basic': [
             ['BGColor','Bold', "Smiley",'Styles', 'Format', 'Font', 'FontSize' "SpecialChar"]
         ],
        'width':"auto",
        'height': 100,
    },
}

CKEDITOR_UPLOAD_PATH = 'ckeditor/'

LOGIN_URL  ="login"
LOGIN_REDIRECT_URL  = "homepage"
LOGOUT_REDIRECT_URL = "homepage"

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

